name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  gcc-build-test:
    name: gcc build & test
    needs: [clang-formatting-check]
    runs-on: kuzu-self-hosted-testing
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r tools/python_api/requirements_dev.txt

      - name: build
        run: CC=gcc CXX=g++ make release NUM_THREADS=32

      - name: test
        run: CC=gcc CXX=g++ make test

  gcc-make-debug:
    name: gcc make debug
    needs: [ clang-formatting-check ]
    runs-on: kuzu-self-hosted-testing
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r tools/python_api/requirements_dev.txt

      - name: debug
        run: CC=gcc CXX=g++ make debug NUM_THREADS=32 ASAN=1

      - name: test
        run: CC=gcc CXX=g++ make test

  clang-build-test:
    name: clang build & test
    needs: [clang-formatting-check]
    runs-on: kuzu-self-hosted-testing
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install --user -r tools/python_api/requirements_dev.txt

      - name: build
        run: CC=clang-14 CXX=clang++-14 make release NUM_THREADS=32

      - name: test
        run: CC=clang-14 CXX=clang++-14 make test

  clang-formatting-check:
    name: clang-formatting-check
    runs-on: kuzu-self-hosted-testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Sarcasm/run-clang-format
          path: run-clang-format
      - run: python3 run-clang-format/run-clang-format.py --clang-format-executable /usr/bin/clang-format-11 -r src/
      - run: python3 run-clang-format/run-clang-format.py --clang-format-executable /usr/bin/clang-format-11 -r test/

  benchmark:
    name: benchmark
    needs: [gcc-build-test, clang-build-test]
    runs-on: kuzu-self-hosted-benchmarking
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install --user -r tools/python_api/requirements_dev.txt

      - name: build
        run: make release NUM_THREADS=30

      - name: benchmark
        run: python3 benchmark/benchmark_runner.py --dataset ldbc-sf100 --thread 1
